### ISSUE TITLE
Which Interface for the General Options Dialog?

### ISSUE THREAD

**Issue by deaspo** [africanmathsinitiative/Instat#1028]
Hi everyone @africanmathsinitiative/instat , am doing a quick poll on what interface should we use for the General options dialog. Below are the two interfaces I would like people to choose from:
a) **GOptionsA**
![goptionsa](https://cloud.githubusercontent.com/assets/10347760/13601971/c0799952-e544-11e5-8bfc-4a6b01cd4b4c.PNG)
b) **GOptionsB**
![goptionsb](https://cloud.githubusercontent.com/assets/10347760/13601972/c07e210c-e544-11e5-99f7-2a94adc7fa5c.PNG)

Please vote for the interface you would prefer by either commenting GOptionsA or GoptionsB. Thanks.

**Comment by nyagishira** [comment]
option A

**Comment by dannyparsons** [comment]
Thanks for doing these two examples for us to look at. 
I assume you are only referring to the navigation part of the dialogs? Because there are lots of other differences like the general form formatting, top right buttons etc.

A vote can be useful but only if people provide reasons for their choice, so that there can be a discussion towards agreement between everyone. Only stating your choice won't be that useful in making a final decision.

**Comment by rdstern** [comment]
GOptionsA

Roger

**Comment by deaspo** [comment]
Please look at #1036

**Comment by maxwellfundi** [comment]
I vote for GOptionsA

Regards
Maxwell Fundi
|| Phone :+254728508241||

**Comment by dannyparsons** [comment]
What's implemented now is both tabs and the tree structure. Happy for it to be changed but it is functional already.
