### ISSUE TITLE
New dialogue for Model > One Variable > Use Model

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/Instat#1763]
This also has a simple main dialogue, namely
1) Usual selector within a data frame, with just objects of the fitdist type - (or bootdist).
2) A single receiver
3) A checkbox "Produce bootstrap"
4) A second checkbox "Save Bootstrap Object", which is only accessible if the "Produce Bootstrap" is checked.
5) The first sub-dialogue is now called "Bootstrap Options".  We need to look at what possible options are.  Number of iterations is the obvious one, where the default is 1001.  A second one is a checkbox for Nonparametric.  The default is parametric.  I don't quite understand the implications of this.
6) The second is as before and includes all the contents of the previous Fit Model.
7) In addition the important extra option is called quantile.  This is a tab on its own.  It takes a set of probabilities and produces the quantiles.  There should be a pull-down control with some examples of probabilities, and the facility to type in your own.  Examples will be 0.1,...0.9, and 0.25, 0.5, 0.75.
8) the confidence level is also specified, with 0.95 being the default.  We don't need to bother about one-sided intervals.
9) The results will depend on whether the bootstrap is available.  If so, then it is used.  If not, then the fitdist object is used.
10) Ideally we should be able to save the results to a new data frame.  But that can wait for now.

Roger

**Comment by lilyclements** [comment]
I have started to have a look at this and have some questions and points:

On point 8) you discuss the confidence interval. I was just wondering where you wanted this placed - did you mean for it to be in the subdialog under the quantiles tab?

I've looked into the bootdist() function to just have a look at the options. What would we allow the maximum number of iterations to be? To get an idea, I tried 10000 on R and it froze for around ten minutes so I eventually pressed esc.
10000 is a lot of iterations, to be fair, but since I am not familiar with bootstrapping I'm not sure of the sort of range one would go for.

As for the parametric option, it seems to be that:
Non-Parametric works off sampling from the dataset
Parametric works off sampling from the distribution
As a result, Non-Parametric is not as good when there is a small sample size or if the data is not identically and independently distributed. (Or for other "technical reasons", however, I could not find what these other reasons were in my googling)
The other options within bootdist() work fine regardless if it is param or non-param. 

Lily

**Comment by rdstern** [comment]
The confidence intervals are only possible when you have the bootstrap.  So they would not be available unless there is a bootstrap object.  This could perhaps be through checking in the form whether the bootstrap object is used, or the ordinary object.

On the maximum for the bootstrap, the number of iterations will change as machines become more powerful.  The default is (I think) 1001.  It should be possible to do less.  I think they use about 100 as a test, so they fit with CRAN testing times.  Then, on more I guess you would either want no limit, so they type the number in - then it is their problem.  If you are using an up-down control  then I think you are correct - 5000, or (at most now) 10,000 would be the limit.   It is an example where we would want to break out of a command if needed.  I will check this with Danny.

Cheers

Roger

**Comment by lilyclements** [comment]
I have a few questions/queries about the graphs for this dialog.

So, when "bootdist" is being used, the plot we can use is "CIcdfplot" and looks like a CDF plot with Confidence Intervals.
I cannot execute the code on r successfully to be able to alter the CI on this plot, however.
However, this plot can have CI.output="quantiles". These quantiles in the CIcdfplot cannot be customised - or at least, I cannot find a way to do this!

The other plots used here are the same as in FitModels (CDF, PP, etc)

Obviously CIcdfplot can only be used with bootdist. Where should I put this option of this plot? I could put it on the dialog, or under the "bootdist options" sdg? Or would we want it on "fit model" sdg with the other plots for non-bootdist models? 
I feel the latter could work if I label it something like "CDF with Confidence Intervals" (and have it disabled if bootstrapping isn't selected).



Final Point is to do with the Quantiles.
So the code is quantile(x =... , probs =... )
For the "probs =" it can be used in two ways, if I do
probs = c("") then the user can specify the probability points they are interested in
That is, for the probability points 0.1,...,0.9 they have to write out
"0.1, 0.2, 0.3, ... "

If I do
probs = seq("min", "max", "increments") then the user can specify the minimum P and maximum, and then the spacing of it
That is, for the probability points 0.1,...,0.9 they have to do
"0, 1, 0.1"

The former is more work for the user, however, it is more flexible.
The latter I feel is "neater", however.
What are your thoughts?
