### ISSUE TITLE
dlgGeneralForGraphics

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/Instat#2112]
dlgGeneralForGraphics does not look complete and crashes if I press "Save Graph". Should I disable it?

**Comment by dannyparsons** [comment]
It's quite important so we should try get it fixed if possible. When are the errors? It hasn't crashed yet when I used it.

**Comment by lilyclements** [comment]
That's strange as it's not crashing anymore. I've tried playing around to get it to re-crash but can't find how!
What do we expect to go into the selector out of interest?

**Comment by dannyparsons** [comment]
Do you mean the list box on the main dialog? That's the list of layers.

**Comment by dannyparsons** [comment]
There may be ways to crash the dialog by doing silly things with layers, this isn't a huge priority to fix right now.

**Comment by FrancoisJRenaud** [comment]
There are plenty of problems with this dialogue. Starting with the fact that there is no way to select the dataframe. If you change tabs inbetween two uses of generalforgraphics, some things are kepts from previous dataframe... etc. These lead to major crashes... I suggested that if we don't disable it, we add a notice on this dialogue saying that it is in construction and may trigger crashes, because they will be coming from several places. Don't know what you think of this. About the dataframe selection could be a good thing to add before beta ( @rdstern @dannyparsons @volloholic ?) . I can work on this if that's desired.

**Comment by dannyparsons** [comment]
I don't know what the purpose of selecting a data frame would be for - different layers can have different data frames.
Let's have a think tomorrow about disabling. I can have a look at it too, to see if anything can be done to avoid crashes without having to disable.

**Comment by FrancoisJRenaud** [comment]
Mhm, yes, got confused about this. Ok, still dataframe management is source of crashes as well...

**Comment by dannyparsons** [comment]
What do you mean by that?

**Comment by FrancoisJRenaud** [comment]
Let me do some systematic testing and report here.

**Comment by dannyparsons** [comment]
If it crashing when you do something like use different data frames on different layers and then don't take care of aesthetics properly then that's ok, we should just warn in release notes that we don't yet catch all these errors.

**Comment by lilyclements** [comment]
I assume it is okay to close this issue now?
