### ISSUE TITLE
Dlg Column Structure- Reset not working when the dlg is reopened

### ISSUE THREAD

**Issue by stevenndungu** [africanmathsinitiative/Instat#2152]
In this dialogue, when you click OK for the first time then reopen the dialogue; 
-Clicking Reset button Clears the Receivers, then Repopulates immediately the  existing column names. Thus eventually the dialog is not set to default as expected. 
This is what happens, 
When the SetDefault() subroutine is called on Click_reset(). SetColumnStructureInReceiver() is called as well, Stepping deeper in the method; method AddItemsWithMetadataProperty() ...frmMain.clsRLink.SelectColumnsWithMetadataProperty(Me, strCurrentDataFrame, strProperty, strValues)... SelectColumnsWithMetadataProperty() clears the column names by  ucrCurrentReceiver.Clear() then  ucrCurrentReceiver.Selector.LoadList()  REPOPULATES under the same subroutine.  This makes the whole aim of resetting to default unachieved. 

Somebody can help in that. Thanks
Steven

**Comment by dannyparsons** [comment]
@stevenndungu it's good you've noticed this and looked into the details. This dialog is quite different to most others. When we reset, instead of clearing receivers, for this dialog we want reset to "reset" the receivers to show the current variables that are in each category. So what it's doing is correct.
If you reopen the dialog - then change the receivers, it should go back to the variables it had in before.
This might be easier to understand by looking at the Hide dialog - it does the same. Reset puts the currently hidden columns in the receiver.

**Comment by stevenndungu** [comment]
OK fine. I thought it should work normally as other dialogues. Thanks.

**Comment by maxwellfundi** [comment]
Can this be closed @stevenndungu ?

**Comment by stevenndungu** [comment]
Yes, that can be closed. Confirmed with Danny and Francois
