### ISSUE TITLE
Use model selector

### ISSUE THREAD

**Issue by stevekogo** [africanmathsinitiative/Instat#2201]
@dannyparsons , @rdstern The use model dialogue in Model>Two variable>Use model has the general selector with variables as the title of the list box. I suggest we edit the title to models its "variables" are models.

**Comment by stevekogo** [comment]
Again, we have different use model menus corresponding to the type fit we are carrying out. Does it mean we will be limiting the models to be selected in the Use model selector to the ones from a specific fit? If not, then we should enable the other Use model menus and link the same use model dialogue.

Another option is to have one use model menu which caters for all models.

**Comment by stevekogo** [comment]
@rdstern , @dannyparsons Please comment on this issue?

**Comment by dannyparsons** [comment]
Good for discussion. I think we leave as is for the beta, and put a note that we are considering different options for this.

**Comment by stevekogo** [comment]
This is OK. @dannyparsons  or @rdstern can label this issue with an appropriate tag.

**Comment by stevekogo** [comment]
@dannyparsons Can we have a discussion on how we can address this issue?

**Comment by dannyparsons** [comment]
For the titles - we have something set up to do this I think. In the receiver you can set `strSelectorHeading` which is the string it will use as the heading in the selector when it's the current receiver. 
It's a property of the receiver because the selector isn't always used for the same thing on the same dialog, so each receiver can set this. You could try setting this on some of the model dialogs. It would then be good for other dialogs to change the heading like the ones where we select objects or graphs etc.

On the second point, I think that needs discussion with Roger and David as well. My understanding was we do want different Use Model dialogs because they do different things depending on the number of variables. That would mean we do want to only see models from a specific fit in those dialogs. How we achieve this and how urgent it is would need some discussion. I think the climate work may take over very soon.
