### ISSUE TITLE
Boolean Layer Parameters

### ISSUE THREAD

**Issue by FrancoisJRenaud** [africanmathsinitiative/Instat#2245]
As @rdstern asked for the varwidth boolean layer parameter in boxplot, these parameters now simply appear as tick boxes on the ucrLayerParameters and don't display the combobox with TRUE or FALSE when ticked any-more. For some parameters, with default value FALSE, and the appropriate name, this is very nice. 

However, think of a parameter such as show.legend, with default value NA, that is in philosophy TRUE. When unticked it is not added as a parameter and takes default TRUE (NA). Then when ticked ? Is it set to TRUE again ? Then how do we set it to FALSE? Or does it take the other value (non default, which is here FALSE) when ticked ? Then we would see: show.legend ticked, which would mean "don't show legend". Neither of these quite work. 

Any boolean layer parameter with default TRUE, for which we want to set FALSE does not work sensibly with this implementation. I like the idea that when a parameter is ticked, it will be added as a parameter for clsGeomFunction. Then the value of that parameter can be decided in the box of values that appear next to it. Might be nice to keep some of the boolean layer parameters like varwidth in the current implementation. However for coherence reasons I would advocate for the previous implementation.

**Comment by dannyparsons** [comment]
For consistency, I think we should keep the combo box for all layer parameters, even TRUE or FALSE parameters. It looks a bit unnatural when it's only TRUE/FALSE, but this is not our main concern on this sub dialog - it's for advanced use. If the parameter is common enough, like `varwidth` for boxplots, then we can also have it on the main dialog (as we do), and there we can make it more user friendly.

For `show.lengend`, we can add that third option, so the type could change to list to allow this. It would be nice if it said something like "Automatic" instead of "NA", but I think would require deeper changes to controls, and it's not a priority. If the TRUE/FALSE/NA is a common combination for layer parameters, we could add it as another type, maybe "boolean+" for example.

**Comment by FrancoisJRenaud** [comment]
Good ! Do you want me to apply these changes ? I can do the ucrGeom one of course, the other one as you want...
