### ISSUE TITLE
Facets tab on Plot Options

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/Instat#2264]
Generally this is still not working perfectly. Some controls are made visible/invisible at the wrong time - I won't detail as it's easy to check.

Then a suggestion for change of implementation: 
When I did facets by Station column which has 16 levels, I got all 16 plots in one row, which doesn't look nice. I expected it would do facet_wrap which would do 4x4 as the default. Currently we have to specify, "fix number of rows" to get facet_wrap. I suggest the choice is either auto (which lets wrap decide the layout) or fix (where user specifies rows), but in both cases it does wrap. And when faceting by 1 column only, I think it should only do grid if you check Margins, in which case, you can't choose number of rows.

That seems sensible to me, but I haven't been involved with this as closely. Is there any other reason part from margins to do grid instead of wrap with one variable?

**Comment by FrancoisJRenaud** [comment]
> That seems sensible to me, but I haven't been involved with this as closely. Is there any other reason part from margins to do grid instead of wrap with one variable?

I don't think so... I was actually surprised to see that grid is the default when 1 variable. But now that I think of it, inititially _fix number of rows and columns_ was ticked by default which is why. But then I don't think it's very intuitive to have to _fix number of rows or columns_ by default. I would rather work on the if else mehtod that decides whether grid or wrap is used and leave _fix number of columns and row_ unticked by default.

Yup we will get this clean on Monday. I suggest @maxwellfundi  does the changes and then we check together that everything is fine ? Does that work for you @maxwellfundi ?

**Comment by maxwellfundi** [comment]
Yeah it does.

**Comment by rdstern** [comment]
I am wondering what the plans are for this.  We used to get facets for monts easily as 3 by 4 when there were 12.  That worked well for the Lesotho team.  It would be good to get it working again.

**Comment by FrancoisJRenaud** [comment]
Yes, it has been on standby because sdgPlots that was used on a pull request. Either @maxwellfundi or myself will have done something about it tomorrow.

**Comment by maxwellfundi** [comment]
@dannyparsons  please close this too. We fixed it a long while ago

thanks
