### ISSUE TITLE
Bug on Transform sub-menu

### ISSUE THREAD

**Issue by stevenndungu** [africanmathsinitiative/Instat#2501]
There is a bug on Climatic >Prepare>Transform. Somebody can help - It breaks whenever one wants the dialogue displayed.  Thanks.

**Comment by stevenndungu** [comment]
@Lunalo, this might be easy solve. I have not been able to solve it. Thanks

**Comment by dannyparsons** [comment]
@stevenndungu thanks for writing this up as an issue, it's really good that you are spotting bugs and reporting them.
I have fixed the issue of the dialog crashing, which was caused by something in a resource file. But now the controls on the dialog are positioned in the wrong place. @stevenndungu @Lunalo could you just tidy this up? I don't think it needs to function, just look ok.

**Comment by stevenndungu** [comment]
Thanks. This can be closed- just made the changes now.
