### ISSUE TITLE
dlgImportfromODK - bug?

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/Instat#2948]
@stevekogo I'm going to tag you in this as I think you'll know best how to fix it! (I believe you wrote this into the code anyway)

So on Import from ODK, it asks for my password twice:
1. When I click "Find Forms"
2. When I click "OK"

Presumably we only want it to ask for the password the once, (When I click "Find Forms").
Is it possible to remove it for the second time it comes up?

**Comment by dannyparsons** [comment]
This is known because we need to use the password twice - once to get the form names and once to get the data from a form. It's a bit annoying to type it twice but it means we don't store the password anywhere which is more secure for users. There could be ways around this if we look into it a bit though.

**Comment by lilyclements** [comment]
Okay, I see. Thank you for explaining!
