### ISSUE TITLE
Defaults on dlgSort

### ISSUE THREAD

**Issue by maxwellfundi** [africanmathsinitiative/Instat#892]
@dannyparsons Should the radio buttons on dlgSort be putting the parameters into the script even when the R default values selected? 
We believe it would be easier for users if the command was simpler when the defaults are selected. We are proposing to implement this as a users choice under the options menu.

**Comment by maxwellfundi** [comment]
We have now implemented what we proposed in pull request #897.
However when reopening the hidden dlgSort after changing the global options, its not updating correctly

**Comment by maxwellfundi** [comment]
Fixed the issue of updating the global options #on reopening dialog #897

**Comment by dannyparsons** [comment]
Happy for that to be an option. 
My preference would be by default we include default parameters. It will make the code a bit longer, but I think it helps people see the link between the R functions and the dialogs because there is a clearer connection between parameters and dialog options. I find the Import Dataset dialog in R Studio confusing because it tries to be very clever and not add default values to the code. I like what we've done with our. In R Studio I can't work out easily what options I selected on the dialog or modify it quickly because I don't know the parameters.
But interested to hear others views on this @rdstern

**Comment by dannyparsons** [comment]
There is now an option in the Options dialog for the user to specify whether they want to include parameters when the default value is chosen. This should be functioning if people have been referring to `bIncludeDefaultParameters` from `clsInstatOptions` correctly in dialogs.
